name: citmatel_strawberry_brain
description: Brain for CITMATEL's 'strawberry' project

publish_to: "none"

version: 1.0.0-RELEASE.20220301

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.1
  clean_core: ^1.2.3-RELEASE.20220206

  # Visual & Animations
  animations: ^2.0.2
  flutter_zoom_drawer: ^2.1.1
  flutter_animator: ^3.2.1
  page_view_indicators: ^2.0.0
  video_player: ^2.2.10
  circular_menu:
    git:
      url: https://github.com/Aidyl98/circular_menu
      ref: develop
  font_awesome_flutter: ^10.1.0
  pushable_button: ^0.0.3

  # Utils
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.18
  auto_size_text: ^3.0.0

  #Other Modules 
  citmatel_strawberry_dnd:
    path: ../citmatel_strawberry_dnd

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  clean_repo_objectbox: ^0.2.1-SNAPSHOT.20220223


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

#configuration of splash screen, if something change, run: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  background_image: "assets/app_splash_inicial.png"

#configuration of flutter_icons, if something change, run: `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

#configuration of flutter_app_name, if something change, run: `flutter pub run flutter_app_name`
flutter_app_name:
  name: "Áthlos Puzzle"

flutter:
  uses-material-design: true

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 400
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
          weight: 400
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Variable.ttf
          weight: 400
  assets:
    - assets/app_icon.png

    - packages/citmatel_strawberry_brain/assets/character/background_dashboard.jpg
    - packages/citmatel_strawberry_brain/assets/character/background_main.png

    - packages/citmatel_strawberry_brain/assets/app/client_splash_1.mp4
    - packages/citmatel_strawberry_brain/assets/app/client_logo.png
    - packages/citmatel_strawberry_brain/assets/app/dev_logo_flat.png
    - packages/citmatel_strawberry_brain/assets/app/libreria.png
