name: citmatel_strawberry_brain
description: Brain for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.0.1-SNAPSHOT.20211202

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.5.1

  clean_core: ^1.1.2-SNAPSHOT.20211206

  animations: ^2.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true