name: citmatel_strawberry_brain
description: Brain for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.1.0-SNAPSHOT.20211221

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.1.3-SNAPSHOT.20220109

  # Visual & Animations
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^2.1.1
  flutter_svg: ^1.0.0
  flutter_animator: ^3.2.0
  page_view_indicators: ^2.0.0

  video_player: ^2.2.10

  # Utils
  faker: ^2.0.0
  package_info_plus: ^1.3.0
  flutter_countdown_timer: ^4.1.0
  circular_menu: ^1.2.3

  #Other Modules
  citmatel_strawberry_trivia:
    path: ../citmatel_strawberry_trivia

  citmatel_strawberry_hangman:
    path: ../citmatel_strawberry_hangman

  citmatel_strawberry_dnd:
    path: ../citmatel_strawberry_dnd

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0


#configuration of splash screen, if something change, run: `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  image: "assets/app_splash_initial.png"
  color: "#0000FF"

#configuration of flutter_icons, if something change, run: `flutter pub run flutter_launcher_icons:main`
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

#configuration of flutter_icons, if something change, run: `flutter pub run flutter_app_name`
flutter_app_name:
  name: "BRAIN"

flutter:
  uses-material-design: true

  assets:
    - packages/citmatel_strawberry_brain/assets/character/background_dashboard.jpg
    - packages/citmatel_strawberry_brain/assets/character/background_main.jpg

    - packages/citmatel_strawberry_brain/assets/app/client_splash_1.mp4
    - packages/citmatel_strawberry_brain/assets/app/client_logo.png
    - packages/citmatel_strawberry_brain/assets/app/dev_logo_flat.png
