name: citmatel_strawberry_brain
description: Brain for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.1.0-SNAPSHOT.20211221

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.1.2-SNAPSHOT.20211206

  # Visual & Animations
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter_zoom_drawer: ^2.1.1

  # Utils
  faker: ^2.0.0

  #Other Modules
  citmatel_strawberry_trivia:
    path: ../citmatel_strawberry_trivia

  citmatel_strawberry_hangman:
    path: ../citmatel_strawberry_hangman

  citmatel_strawberry_dnd:
    path: ../citmatel_strawberry_dnd

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true